DROP TABLE IF EXISTS TILE;

CREATE TABLE TILE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  letter CHAR(1) NOT NULL
);

INSERT INTO TILE (letter) VALUES('a');
INSERT INTO TILE (letter) VALUES('b');
INSERT INTO TILE (letter) VALUES('c');
INSERT INTO TILE (letter) VALUES('d');
INSERT INTO TILE (letter) VALUES('e');
INSERT INTO TILE (letter) VALUES('f');